name: ci

on:
  push:
    branches: main

jobs:
  docker:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          password: ${{ secrets.DOCKER_USERNAME }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./basic
          push: true
          file: Dockerfile.prod
          tags: richardschiemenz/basic_dashboard:latest