name: ci

on:
  push:
    branches: main

jobs:
  docker:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./basic/
          file: ./basic/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/basic_dashboard:latest